<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Admin 
        User::create(['name' => 'Admin', 'password' => bcrypt('admin'), 'email' => 'admin@admin.com', 'role_id' => '1', 'address' => 'Rumahnya Admin', 'phone_number' => '085750479798']);
        
        //Client
        User::create(['name' => 'Client Kurnia Akbar', 'password' => bcrypt('client'), 'email' => 'client@client.com', 'role_id' => '2', 'address' => 'Rumahnya client', 'phone_number' => '080265228878', 'kuli_specialties' => 'Besi', 'experience' => 'Pernah mengerjakan proyek besar sebagai tukang pasang besi dan baja ringan pada proyek besar', 'kuli_availability' => '0', 'called' => '0', 'works_under' => '22', 'applying' => '1', 'proyek_id' => '1', 'status_id' => '1']);
        User::create(['name' => 'Ahmad clientawan', 'password' => bcrypt('client1'), 'email' => 'client1@client.com', 'role_id' => '2', 'address' => 'Jalan Masih Ada no 420, Jember Utara', 'phone_number' => '080272494794', 'kuli_specialties' => 'Cor', 'experience' => 'Berpengalaman ngecor dan menjadi tumbal proyek', 'kuli_availability' => '1', 'called' => '0', 'works_under' => '22', 'applying' => '1', 'proyek_id' => '1', 'status_id' => '1']);
        User::create(['name' => 'Fulan', 'password' => bcrypt('client2'), 'email' => 'client2@client.com', 'role_id' => '2', 'address' => 'Jalan Rambutan no 123, Queensland', 'phone_number' => '084154858211', 'kuli_specialties' => 'Besi, Mekanik', 'experience' => 'Saya jago di alat dan mesin', 'kuli_availability' => '0', 'called' => '1', 'works_under' => '22', 'applying' => '0', 'proyek_id' => null, 'status_id' => '4']);
        User::create(['name' => 'Vega Hakim', 'password' => bcrypt('client3'), 'email' => 'client3@client.com', 'role_id' => '2', 'address' => 'Perumahan Elitis no 11, Arkansas', 'phone_number' => '089279639128', 'kuli_specialties' => 'Kayu, Besi', 'experience' => 'Berpengalaman mengerjakan hal berbau kayu', 'kuli_availability' => '0', 'called' => '1', 'works_under' => '22', 'applying' => '0', 'proyek_id' => null, 'status_id' => '4']);
        User::create(['name' => 'Marsito Nardi Maulana', 'password' => bcrypt('client4'), 'email' => 'client4@client.com', 'role_id' => '2', 'address' => 'Psr. Aceh No. 127, Kendari 19820, SumBar', 'phone_number' => '081129549083','kuli_specialties' => 'Kayu, Listrik', 'experience' => 'Berpengalaman mengerjakan hal berbau Aspal', 'kuli_availability' => '0', 'called' => '0', 'works_under' => '22', 'applying' => '0', 'proyek_id' => null, 'status_id' => '5']);
        User::create(['name' => 'Dagel Hidayanto', 'password' => bcrypt('client5'), 'email' => 'client5@client.com', 'role_id' => '2', 'address' => 'Gg. Mulyadi No. 529, Pekalongan 80808, SulUt', 'phone_number' => '089581581949',  'kuli_specialties' => 'Keramik, Tembok', 'experience' => '*Ini adalah pengalaman nguli sebagai portfolio client', 'kuli_availability' => '1', 'called' => '1', 'works_under' => '22', 'applying' => '0', 'proyek_id' => '1', 'status_id' => '3']);
        User::create(['name' => 'Gara Luluh Dabukke', 'password' => bcrypt('client6'), 'email' => 'client6@client.com', 'role_id' => '2', 'address' => 'Gg. Panjaitan No. 133, Parepare 15408, Lampung', 'phone_number' => '082869525140',  'kuli_specialties' => 'Kayu', 'experience' => '*Ini adalah pengalaman nguli sebagai portfolio client', 'kuli_availability' => '0', 'called' => '1', 'works_under' => '22', 'applying' => '0', 'proyek_id' => null, 'status_id' => '3']);
        User::create(['name' => 'Dartono Hutagalung', 'password' => bcrypt('client7'), 'email' => 'client7@client.com', 'role_id' => '2', 'address' => 'Jln. Cokroaminoto No. 76, Malang 39623, SulTeng', 'phone_number' => '086972021587',  'kuli_specialties' => 'Kayu, Mekanik', 'experience' => '*Ini adalah pengalaman nguli sebagai portfolio client', 'kuli_availability' => '0', 'called' => '1', 'works_under' => '22', 'applying' => '0', 'proyek_id' => null, 'status_id' => '2']);
        User::create(['name' => 'Argono Nasab Kusumo', 'password' => bcrypt('client8'), 'email' => 'client8@client.com', 'role_id' => '2', 'address' => 'Gg. Cemara No. 119, Sungai Penuh 79177, Bengkulu', 'phone_number' => '085232597482',  'kuli_specialties' => 'Besi, Baja Ringan', 'experience' => '*Ini adalah pengalaman nguli sebagai portfolio client', 'kuli_availability' => '0', 'called' => '1', 'works_under' => '22', 'applying' => '0', 'proyek_id' => null, 'status_id' => '2']);
        User::create(['name' => 'Kambali Sihombing', 'password' => bcrypt('client9'), 'email' => 'client9@client.com', 'role_id' => '2', 'address' => 'Gg. Zamrud No. 680, Binjai 25097, SulTeng', 'phone_number' => '084939707088',  'kuli_specialties' => 'Baja Ringan', 'experience' => '*Ini adalah pengalaman nguli sebagai portfolio client', 'kuli_availability' => '0', 'called' => '1', 'works_under' => '22', 'applying' => '0', 'proyek_id' => null, 'status_id' => '2']);
        User::create(['name' => 'Jaiman Sihombing', 'password' => bcrypt('client10'), 'email' => 'client10@client.com', 'role_id' => '2', 'address' => 'Jr. Bakaru No. 5, Tangerang 94272, Lampung', 'phone_number' => '080688699078',  'kuli_specialties' => 'Ngaduk Semen', 'experience' => '*Ini adalah pengalaman nguli sebagai portfolio client', 'kuli_availability' => '1', 'called' => '0', 'works_under' => '22', 'applying' => '1', 'proyek_id' => '1', 'status_id' => '1']);
        User::create(['name' => 'Prabu Kurniawan', 'password' => bcrypt('client11'), 'email' => 'client11@client.com', 'role_id' => '2', 'address' => 'Jr. Baranangsiang No. 50, Sungai Penuh 73705, KalUt', 'phone_number' => '084858713560',  'kuli_specialties' => 'Tumbal Proyek', 'experience' => '*Ini adalah pengalaman nguli sebagai portfolio client', 'kuli_availability' => '1', 'called' => '1', 'works_under' => '22', 'applying' => '0', 'proyek_id' => '1', 'status_id' => '2']);
        User::create(['name' => 'Hardi Januar', 'password' => bcrypt('client12'), 'email' => 'client12@client.com', 'role_id' => '2', 'address' => 'Dk. Uluwatu No. 754, Palopo 64394, SulBar', 'phone_number' => '080119297328',  'kuli_specialties' => 'Cor, Genteng', 'experience' => '*Ini adalah pengalaman nguli sebagai portfolio client', 'kuli_availability' => '1', 'called' => '0', 'works_under' => '22', 'applying' => '1', 'proyek_id' => '2', 'status_id' => '1']);
        User::create(['name' => 'Panji Wage Dongoran', 'password' => bcrypt('client13'), 'email' => 'client13@client.com', 'role_id' => '2', 'address' => 'Gg. Setiabudhi No. 816, Palangka Raya 91562, JaTim', 'phone_number' => '083970118088',  'kuli_specialties' => 'Genteng', 'experience' => '*Ini adalah pengalaman nguli sebagai portfolio client', 'kuli_availability' => '0', 'called' => '0', 'works_under' => '23', 'applying' => '1', 'proyek_id' => '3', 'status_id' => '1']);
        User::create(['name' => 'Irsad Wibowo', 'password' => bcrypt('client14'), 'email' => 'client14@client.com', 'role_id' => '2', 'address' => 'Gg. Raden Saleh No. 323, Tanjungbalai 19880, SumSel', 'phone_number' => '088978520441',  'kuli_specialties' => 'Genteng', 'experience' => '*Ini adalah pengalaman nguli sebagai portfolio client', 'kuli_availability' => '1', 'called' => '0', 'works_under' => '23', 'applying' => '1', 'proyek_id' => '3', 'status_id' => '1']);
        User::create(['name' => 'Harja Hutasoit', 'password' => bcrypt('client15'), 'email' => 'client15@client.com', 'role_id' => '2', 'address' => 'Ds. K.H. Wahid Hasyim (Kopo) No. 461, Pangkal Pinang 46309, KepR', 'phone_number' => '087960703507',  'kuli_specialties' => 'Ngopi', 'experience' => '*Ini adalah pengalaman nguli sebagai portfolio client', 'kuli_availability' => '0', 'called' => '23', 'works_under' => '23', 'applying' => '1', 'proyek_id' => '4', 'status_id' => '1']);
        User::create(['name' => 'Emas Pratama', 'password' => bcrypt('client16'), 'email' => 'client16@client.com', 'role_id' => '2', 'address' => 'Kpg. Pasirkoja No. 323, Mojokerto 29220, SulUt', 'phone_number' => '088179717613', 'kuli_specialties' => 'Cor, Nembok', 'experience' => '*Ini adalah pengalaman nguli sebagai portfolio client', 'kuli_availability' => '1', 'called' => '0', 'works_under' => '24', 'applying' => '1', 'proyek_id' => '4', 'status_id' => '1']);
        User::create(['name' => 'Mustofa Maheswara', 'password' => bcrypt('client17'), 'email' => 'client17@client.com', 'role_id' => '2', 'address' => 'Jln. Sugiyopranoto No. 575, Samarinda 11573, KalBar', 'phone_number' => '088210720495',  'kuli_specialties' => 'Genteng', 'experience' => '*Ini adalah pengalaman nguli sebagai portfolio client', 'kuli_availability' => '0', 'called' => '0', 'works_under' => '24', 'applying' => '1', 'proyek_id' => '5', 'status_id' => '1']);
        User::create(['name' => 'Fredi Mencurry', 'password' => bcrypt('client18'), 'email' => 'client18@client.com', 'role_id' => '2', 'address' => 'Psr. PHH. Mustofa No. 96, Tanjungbalai 76708, Jambi', 'phone_number' => '085553820811',  'kuli_specialties' => 'Besi', 'experience' => '*Ini adalah pengalaman nguli sebagai portfolio client', 'kuli_availability' => '1', 'called' => '0', 'works_under' => '25', 'applying' => '1', 'proyek_id' => '5', 'status_id' => '1']);
        User::create(['name' => 'Wawan Mandala', 'password' => bcrypt('client19'), 'email' => 'client19@client.com', 'role_id' => '2', 'address' => 'Gg. R.E. Martadinata No. 553, Administrasi Jakarta Utara 49410, NTB', 'phone_number' => '081591537440',  'kuli_specialties' => 'Besi', 'experience' => '*Ini adalah pengalaman nguli sebagai portfolio client', 'kuli_availability' => '1', 'called' => '0', 'works_under' => '25', 'applying' => '1', 'proyek_id' => '6', 'status_id' => '1']);
        
        //artist
        User::create(['name' => 'Dwi artist Putra', 'password' => bcrypt('artist'), 'email' => 'artist@artist.com', 'role_id' => '3', 'address' => 'Rumahnya artist', 'phone_number' => '089603098514']);
        User::create(['name' => 'David Daud', 'password' => bcrypt('artist1'), 'email' => 'artist1@artist.com', 'role_id' => '3', 'address' => 'Perumahan Marjinal no 720, Jember Utara', 'phone_number' => '083091160286']);
        User::create(['name' => 'Saadat Cakrabirawa Prayoga S.Pd', 'password' => bcrypt('artist2'), 'email' => 'artist2@artist.com', 'role_id' => '3', 'address' => 'Jr. Basoka Raya No. 110, Bekasi 79141, KepR', 'phone_number' => '085484386343']);
        User::create(['name' => 'Murti Asmuni Adriansyah M.Pd', 'password' => bcrypt('artist3'), 'email' => 'artist3@artist.com', 'role_id' => '3', 'address' => 'Jr. Suryo No. 285, Sabang 74441, PapBar', 'phone_number' => '084210923132']);
        User::create(['name' => 'Wakiman Hutagalung', 'password' => bcrypt('artist4'), 'email' => 'artist4@artist.com', 'role_id' => '3', 'address' => 'Jln. Abdul Rahmat No. 779, Pontianak 64402, KalTim', 'phone_number' => '086348649061']);


    }
}
